// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNBjJ-9V_rvWwbGJDBbUxgC3PcDdhm9dM',
    appId: '1:1013376549495:web:397b16e6ae1b1f67243c72',
    messagingSenderId: '1013376549495',
    projectId: 'flutter-projects-3a418',
    authDomain: 'flutter-projects-3a418.firebaseapp.com',
    storageBucket: 'flutter-projects-3a418.firebasestorage.app',
    measurementId: 'G-Y69Q4PB6FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSBTyhLQh7gEZOpHhM3wCSiANUXszYI30',
    appId: '1:1013376549495:android:c1911edb5002ab8a243c72',
    messagingSenderId: '1013376549495',
    projectId: 'flutter-projects-3a418',
    storageBucket: 'flutter-projects-3a418.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByZOQZ1RyBllAffgHp-_vJEZUgW0EhYh4',
    appId: '1:1013376549495:ios:851a9485ca06cd35243c72',
    messagingSenderId: '1013376549495',
    projectId: 'flutter-projects-3a418',
    storageBucket: 'flutter-projects-3a418.firebasestorage.app',
    iosBundleId: 'com.prady.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByZOQZ1RyBllAffgHp-_vJEZUgW0EhYh4',
    appId: '1:1013376549495:ios:851a9485ca06cd35243c72',
    messagingSenderId: '1013376549495',
    projectId: 'flutter-projects-3a418',
    storageBucket: 'flutter-projects-3a418.firebasestorage.app',
    iosBundleId: 'com.prady.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNBjJ-9V_rvWwbGJDBbUxgC3PcDdhm9dM',
    appId: '1:1013376549495:web:7418003e2fd42d59243c72',
    messagingSenderId: '1013376549495',
    projectId: 'flutter-projects-3a418',
    authDomain: 'flutter-projects-3a418.firebaseapp.com',
    storageBucket: 'flutter-projects-3a418.firebasestorage.app',
    measurementId: 'G-QB08MWP8BB',
  );
}
